# Generated by Django 3.2 on 2021-08-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(verbose_name='Цитата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quoteapp.author', verbose_name='Автор')),
            ],
        ),
    ]
